name: ecology_project
channels:
  - https://conda.atoti.io
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - matplotlib
  - jupyter_nbextensions_configurator
  - pandas-profiling
  - scikit-learn
  - jupyter_latex_envs
  - category_encoders
  - pandas




